version: "3.9"
services:
 database:
  image: "postgres:latest"
  ports:
  - "5432:5432"
  environment:
   POSTGRES_USER: test
   POSTGRES_PASSWORD: 123
   POSTGRES_DB: test_clients
  volumes:
   - ./server/storage/db.sql:/docker-entrypoint-initdb.d/db.sql
 server:
  build: .
  ports:
  - "5000:5000"
  depends_on:
  - database
  entrypoint: ["/flask_system_monitor/tests/sh_for_tests.sh"]
  env_file:
    - tests/.test.env