version: "3.9"
services:
 server:
  build: server/
  ports:
  - "5000:5000"
  depends_on:
  - database
 database:
  image: "postgres:latest"
  ports:
  - "5432:5432"
  environment:
   POSTGRES_USER: wood
   POSTGRES_PASSWORD: 123
   POSTGRES_DB: clients
  volumes:
    - .:/docker-entrypoint-initdb.d/
