version: "3.9"
services:
 database:
  image: "postgres:latest"
  ports:
  - "5431:5432"
  environment:
   POSTGRES_USER: wood
   POSTGRES_PASSWORD: 123
   POSTGRES_DB: clients
  volumes:
    - .:/docker-entrypoint-initdb.d/
 server:
  build: .
  ports:
  - "5000:5000"
  depends_on:
  - database
  entrypoint: ["/flask_system_monitor/tests/sh_for_tests.sh"]
